// ============================================================================
// THE FORBIDDEN-COLUMN GUARD.
//
// This file used to be the v2 ontology: a prose record of what the isolation
// was, plus a renderer that turned it into the model's prompt. All of that is
// gone. The ontology is now DATA — ai/src/course_ai/ontology/data.py — and a
// graph proves over that data that no `jamas` column is reachable
// (P1..P4 over the bridged tools, P5 over the native ones, in
// ai/src/course_ai/ontology/graph.py). The guarantee went from comment to
// theorem.
//
// What is left here is the RUNTIME half of that theorem, and only that: two
// functions that read the generated artifact and refuse to let a forbidden
// column leave. They carry no copy of the truth. One source
// (ai/src/course_ai/ontology/data.py), one artifact (api/src/ontologia.json),
// two readers (this file and data/internal/guard).
//
// WHAT WAS DELETED, and why nothing was lost — so nobody restores it looking for
// coverage that moved:
//
//   ONTOLOGY, PLANNED_ONTOLOGY, ColumnRecord, TableRecord
//       The v2 prose record. Nothing imported them.
//
//   renderForModel()
//       Rendered the v2 prompt. The prompt the model actually receives is
//       emitted by the AI service (GET /ontologia/prompt), and this function had
//       not been on that path for a long time. api/test/isolation.mts asserted
//       against it — «the ontology the model sees does not name pass_hash» —
//       which read like a guarantee and checked a document nobody serves. That
//       is the third time in this repository a guard has gone dark while
//       reporting green.
//       The real prompt IS checked, and more strictly: ai/tests/test_render.py
//       test_the_ontology_block_does_not_name_what_is_forbidden and
//       test_not_even_the_whole_prompt_names_a_qualified_column, both
//       parametrised over BOTH languages and also checking qualified names like
//       `users.pass_hash`.
//
//   ONTOLOGY_META
//       Its docstring said «for the boot log and /api/version». Neither used it:
//       server.ts does not import this module at all, and /api/version returns
//       versions, hit counts and the AI url. If the artifact's sha is ever wanted
//       there, it is three lines and it should be added when somebody reads it.
//
// FILENAME: `ontologia.json` keeps its Spanish name deliberately. It is generated
// by the Python side and read here at import time, so renaming it is a
// coordinated change across two services. Its CONTENT keys — `prohibidas`,
// `violaciones` — and the data values — `publico`, `propio`, `agregado`,
// `jamas`, `gratis`, `de_pago` — are DATA and are not renamed either.
// ============================================================================

/**
 * The PART of the generated artifact this module reads.
 *
 * Deliberately partial, and the same choice data/internal/guard makes: typing
 * fields nobody reads would make this interface a second, partial specification
 * of a document the Python side owns, and the two would drift. The artifact has
 * more keys — `clases`, `herramientas`, `prompt_sha`, `orden_borrado` and others
 * — and ai/src/course_ai/ontology/export.py is where their shape is defined.
 */
interface GeneratedOntology {
  /** table -> the columns that may never leave the server */
  prohibidas: Record<string, string[]>;
  violaciones: unknown[];
}

// The artifact is read ONCE at boot. If it is missing, the server does not start
// halfway: without the list of forbidden columns the guard protects nothing, and
// carrying on would be worse than stopping.
//
// The import is dynamic so the failure can be caught and re-thrown with the
// command that fixes it. A static import would give a bare ERR_MODULE_NOT_FOUND,
// and the whole point of this block is the message. It still counts as a program
// import, so `tsgo -p .` copies ontologia.json next to the emitted ontology.js.
let GENERATED: GeneratedOntology;
try {
  GENERATED = (await import('./ontologia.json', { with: { type: 'json' } }))
    .default as unknown as GeneratedOntology;
} catch (e) {
  throw new Error(
    'api/src/ontologia.json is missing (generated by `uv --directory ai run ai-export`). '
    + 'Without it, assertNoForbidden does not know which columns to block. '
    + (e instanceof Error ? e.message : String(e)));
}
if (GENERATED.violaciones?.length) {
  throw new Error(`ontologia.json declares ${GENERATED.violaciones.length} isolation violation(s): the server does not start with a documented leak`);
}

/**
 * Columns that cannot leave the server by any path. Comes from the generated
 * artifact.
 *
 * Fails CLOSED on an unknown table.
 *
 * This used to answer `[]` for any name it did not recognise, which made
 * `assertNoForbidden('some_table', row)` a silent no-op. The ontology declared
 * nine tables; the database had twelve. `lesson_text` was guarded by a call that
 * checked nothing, and `reset_tokens` — password-reset token hashes — was
 * unguardable by construction.
 *
 * A guard that approves what it never inspected is worse than no guard: it reports
 * safety. Now an undeclared table throws, so the failure is a loud startup or test
 * error instead of a leak that looks green.
 */
export function forbiddenColumns(table: string): string[] {
  const cols = GENERATED.prohibidas[table];
  if (!cols) {
    throw new Error(
      `ontologia: table '${table}' is not declared. The guard cannot approve what it does not know: `
      + `declare it in ai/src/course_ai/ontology/data.py and regenerate with 'uv run ai-export'. `
      + `Declared: ${Object.keys(GENERATED.prohibidas).sort().join(', ')}.`);
  }
  return cols;
}

/** Throws if a row carries a forbidden column. Called before data is returned. */
export function assertNoForbidden<T>(table: string, row: T): T {
  const forbidden = forbiddenColumns(table);
  const found = Object.keys((row ?? {}) as Record<string, unknown>).filter((k) => forbidden.includes(k));
  if (found.length) {
    throw new Error(`ontologia: ${table} tried to return ${found.join(', ')}`);
  }
  return row;
}
