"""Query preparation and concept scoring. A pure function, top to bottom.

WHAT IS WRONG WITH COUNTING SUBSTRINGS, measured

Node's `buscar_en_curso` lowercases the query, strips accents, keeps the words
longer than two characters (at most six of them) and scores a lesson by how many
of those words occur as SUBSTRINGS of each of its text fields. Three consequences,
each one measured over the real corpus rather than reasoned about:

  1. `length > 2` is not a stopword rule. In Spanish it lets through
     `que como por con una modelo`, and in English `and model that the not you
     with`. They are the most frequent words in the language, so they hit almost
     every lesson and the ranking is decided by noise.
  2. SUBSTRING matching makes them worse than merely useless. `con` is inside
     *contexto*, *conversacion* and *consola*; `que` is inside *porque* and
     *aquel*. A stopword does not just add a point everywhere — it adds points in
     the places that look most like a real hit.
  3. Nothing bridges vocabulary. `aleatorio` occurs nowhere in twelve lessons, so
     «como lo hago menos aleatorio» scores zero and the model answers from memory.
     Worse, `random` occurs exactly once, in LESSON 2, so «how do i make it less
     random» routes confidently to the wrong lesson. That is not a miss to be
     out-scored; it is a poisoned route, and only an authored synonym fixes it.

WHAT THIS DOES INSTEAD

  · Whole WORDS, never substrings, after a light stem so `fotos`/`foto` and
    `puntajes`/`puntaje` are the same key.
  · An explicit stopword list per language, containing the measured survivors
    of the `length > 2` filter plus the rest of the question scaffolding
    (`how why what does`), all of which are exactly the words that match
    everything. A dropped word scores ZERO — it cannot out-rank anything,
    which is the property `test_retrieval.py` asserts by name for `por` and
    `que`.
  · A bilingual SYNONYM table from the beginner's word to a public glossary term.
    Every entry is drawn from the measured «absent from the corpus» list, which is
    the honest place for authored vocabulary: a word the corpus does not contain
    cannot be a copy of the corpus. This is the half no scoring change in Node can
    replace.
  · Three signals, each of them REPORTABLE, because the model has to be able to
    say where it found the answer: a glossary term matched, a synonym bridged, or
    a phrasing overlapped. `Ranked.reasons` carries all three and
    `entender_pregunta` hands them to the model as `por_que`.

The index is not consulted here and neither is the network: everything on this
page is a function of its arguments, so the routing half of the accuracy table in
test_retrieval.py runs with no database.

THE COLUMN IT IS COMPARED AGAINST DOES NEED NODE, and that is deliberate. It used
to be a dict typed by hand into ai/tests/queries.py, documented as «the measured
output of the real ranking over the real content» — and it disagreed with the real
scorer on 53 of 138 entries, so every «+N points» in this package was quoted
against a column no run produces. It is now generated by
scripts/emit-search-baseline.mjs, which calls `buscar_en_curso` itself. Slower,
and the only version of it that can be believed.
"""

from __future__ import annotations

import math
import unicodedata
from collections.abc import Iterable, Mapping, Sequence
from dataclasses import dataclass
from functools import lru_cache
from typing import Literal

from .concepts import CONCEPTS, Concept, phrasings, terms

Lang = Literal["es", "en"]

# The measured survivors of Node's `length > 2` filter come first, because they are
# the concrete defect: ES `que como por con una modelo`, EN `and model that the not
# you with`. The rest is the same category — question scaffolding and function
# words that occur in every lesson — and leaving them in would be keeping the bug
# for the words that happen to be four letters long.
#
# The list is deliberately SHORT, and that was measured too: a first version also
# dropped `make things get much many algo cosa puedo donde cuanto`, and routing
# fell to 46% because those words carry the topic in a beginner's sentence — «why
# does it make things up» has NOTHING left once `make` and `things` are gone, and
# the router answered `sin_ruta` to the single most common question in the set. A
# stopword list is not «words I do not like»; it is the words that occur in EVERY
# lesson, and nothing else belongs in it.
#
# `modelo`/`model` are here even though `modelo` is a glossary term. They were
# measured as two of the worst offenders, they are what the whole product is about
# so they appear in every lesson, and the concept they would route to (lesson 3)
# is reachable through `perilla`, `parametro` and `peso`, which are specific.
STOPWORDS_ES: frozenset[str] = frozenset({
    "que", "como", "por", "con", "una", "modelo",
    "uno", "unos", "unas", "para", "pero", "los", "las", "del", "mas", "sus",
    "sin", "son", "esta", "este", "esto", "eso", "ese", "esa", "esos", "esas",
    "hay", "muy", "asi", "tan", "porque", "cuando", "otra", "otro", "cual",
    "cuales", "desde", "hasta", "sobre", "entre", "aqui", "alli",
    # The interrogatives, and this one is a correctness argument rather than a
    # preference: `how why what when where who` are already dropped on the English
    # side, so leaving `quien donde cuanto` in would mean the two languages run
    # different rules over the same map. It is also a measured precision bug —
    # `quien` occurs in exactly one concept's phrasings, so it scored the ceiling and
    # «quien gano el mundial» routed confidently to lesson 1, which is the
    # confident-wrong answer this whole module exists to stop.
    #
    # THE COST, MEASURED, because it is not free — and re-measured after FLOOR moved
    # to W_TERM, because a cost quoted from a run of a different scorer is a number
    # nobody can trace: routing over the 138-question table goes from 62 to 61 and
    # the composition from 103 to 103. ONE question was being carried by a question
    # word, which is to say it was right by coincidence, and the floor has since
    # taken over most of what this list was doing.
    # Four more candidates were rejected for costing a real point and
    # buying nothing: `puedo puede necesito sirve` are not interrogatives, they are
    # ordinary verbs that happen to open a question, and they occur inside real
    # questions about the course («puedo confiar en lo que me dice»).
    "quien", "quienes", "donde", "cuanto", "cuanta", "cuantos", "cuantas",
    "quiero",
})
STOPWORDS_EN: frozenset[str] = frozenset({
    "and", "model", "not", "que", "that", "the", "with", "you",
    "how", "why", "what", "when", "where", "who", "whom", "does", "did",
    "are", "was", "were", "for", "can", "could", "will", "would", "should",
    "this", "these", "those", "they", "them", "there", "then", "from", "into",
    "its", "his", "her", "about", "than", "very", "such", "each",
    # Same rule as the Spanish interrogatives above: intent, not topic. `need` is
    # deliberately NOT here — it cost a point and bought nothing, because «does it
    # need many examples» is a real question about lesson 1 and `need` is the word
    # carrying it.
    "want", "wants", "please",
})

# The beginner's word -> a PUBLIC glossary term. Every key is a word measured as
# ABSENT from the searchable corpus, which is what makes this table safe to author
# here as well as necessary: a word the twelve lessons never use cannot be a
# derivative of them, and no change to Node's scorer can ever match it.
#
# The values are glossary terms and aliases, so `ai-check-concepts` validates both
# ends of every arrow: the key against nothing (it is authored), the value against
# the glossary `glosario` really answers with.
#
# A SYNONYM HAS TO BE SPECIFIC or it is a stopword with extra steps, and three
# entries were removed on that ground after being measured. `today` -> cutoff took
# «where do i start today» off lesson 12 by 0.04 points, beating a phrasing that
# holds the whole question verbatim; `remember` -> context took «will it remember
# tomorrow what i said» off lesson 4, which is the lesson about exactly that.
# `memory` stayed, because a beginner saying «memory» does mean the context window
# and nothing else. The test for a candidate is not «is it a plausible gloss» but
# «does it belong to ONE concept».
SYNONYMS_ES: Mapping[str, tuple[str, ...]] = {
    "aleatorio": ("temperatura",), "aleatoria": ("temperatura",),
    "aleatoriedad": ("temperatura",), "azaroso": ("temperatura",),
    "creatividad": ("temperatura",), "creativo": ("temperatura",),
    "creativa": ("temperatura",), "repetible": ("temperatura",),
    "estable": ("temperatura",), "estables": ("temperatura",),
    "identico": ("temperatura",), "identica": ("temperatura",),
    "alucina": ("alucinacion",), "alucinacion": ("alucinacion",),
    "confiar": ("alucinacion",), "confio": ("alucinacion",),
    "miente": ("alucinacion",), "mentira": ("alucinacion",),
    "falso": ("alucinacion",), "falsa": ("alucinacion",),
    "verdad": ("alucinacion",), "seguro": ("alucinacion",),
    "parametro": ("perilla",), "parametros": ("perilla",),
    "prompt": ("prompt",), "prompts": ("prompt",),
    "generico": ("prompt",), "generica": ("prompt",),
    "olvida": ("contexto",), "olvido": ("contexto",),
    "memoria": ("contexto",), "recuerda": ("contexto",),
    "entiende": ("probabilidad",), "cerebro": ("perilla",),
    # `costo`/`cuesta` are lesson 4's own subject («cuanto cuesta una respuesta»)
    # and they stay. What they must not do is answer «cuanto cuesta el CURSO», and
    # that is not fixed here: `intent.py` matches the product noun before this
    # table is ever consulted. Removing the synonym instead would have cost the
    # real question to fix the wrong one.
    "robot": ("perilla",), "costo": ("inferencia",), "cuesta": ("inferencia",),
    "gratis": ("inferencia",), "actualizado": ("fecha de corte",),
    "reciente": ("fecha de corte",), "noticias": ("fecha de corte",),
    "costumbre": ("habito",), "constancia": ("habito",),
}
SYNONYMS_EN: Mapping[str, tuple[str, ...]] = {
    "random": ("temperature",), "randomness": ("temperature",),
    "randomly": ("temperature",), "creative": ("temperature",),
    "creativity": ("temperature",), "repeatable": ("temperature",),
    "consistent": ("temperature",), "reliable": ("temperature",),
    "stable": ("temperature",), "identical": ("temperature",),
    "hallucination": ("hallucination",), "hallucinate": ("hallucination",),
    "hallucinates": ("hallucination",), "trust": ("hallucination",),
    "lie": ("hallucination",), "lies": ("hallucination",),
    "lying": ("hallucination",), "false": ("hallucination",),
    "true": ("hallucination",), "truth": ("hallucination",),
    "invent": ("hallucination",), "invented": ("hallucination",),
    "confidently": ("hallucination",),
    "parameter": ("parameter",), "parameters": ("parameter",),
    "weight": ("weights",), "weights": ("weights",),
    "prompt": ("prompt",), "prompts": ("prompt",),
    "generic": ("prompting",),
    "forget": ("context",), "forgets": ("context",), "forgot": ("context",),
    "memory": ("context",),
    "understand": ("probability",), "understands": ("probability",),
    "brain": ("parameter",), "machine": ("machine learning",),
    "cost": ("inference",), "costs": ("inference",), "expensive": ("inference",),
    "free": ("inference",), "updated": ("cutoff",), "recent": ("cutoff",),
    "news": ("cutoff",),
    "habit": ("habit",), "routine": ("habit",), "practice": ("practice",),
}

# The shortest word that carries topic. Node used `length > 2` and that is kept,
# because the words it excludes in both languages are articles and prepositions —
# the disagreement is about the ones it LETS THROUGH, not about this bound.
MIN_WORD = 3

# What a signal is worth. The three are deliberately close: a glossary term is the
# strongest single piece of evidence, a bridged synonym is a term arrived at
# indirectly so it is worth slightly less, and a phrasing overlap is worth what its
# coverage says it is worth. Nothing here is worth zero and nothing dominates
# absolutely, so two weak signals can outvote one strong one — which is what makes
# «hay una perilla para la creatividad» land on temperature (perilla + creativa)
# rather than on parameters (perilla alone).
W_TERM = 5.0
W_SYNONYM = 4.0
W_PHRASE = 4.104

# Below this, `entender_pregunta` says `sin_ruta` instead of naming a lesson. The
# model is then told to say it does not know rather than answer from memory, which
# is the failure the whole module exists to prevent: a confident wrong lesson is
# worse than an admitted miss, because the student cannot tell.
#
# WHY IT IS W_TERM, and why it may not be a number picked by hand.
#
# The floor's job is to say what the LEAST evidence that may name a lesson is, and
# there is only one defensible answer: one glossary term of the course. «que es un
# token» is one term and has to route; anything weaker than one term must not.
#
# It used to be 3.0, which is BELOW W_PHRASE (4.104), and that inequality was the
# defect. One query word shared with one phrasing of one concept cleared the floor
# and routed, at confianza 0.34. Measured over the 182 pooled fixture questions
# (138 about a lesson, 44 about anything else): that bucket was 23 right and 24
# wrong — 49%, a coin flip — and it was 47 of the 115 answers the tool gave, so 41%
# of everything it said was decided by one ordinary word. «can it tell me the
# weather right now» routed to lesson 7 on `tell`; «it gave me a book title that
# does not exist» to lesson 8 on `book`;
# «cuanto cuesta el curso completo» to lesson 4 at confianza 1.0. In every case
# `por_que` named the phrasing, so the wrong route read as evidence-backed.
#
# WHAT IT COSTS, measured, because it is not free: the composed pipeline drops
# from 107 of 138 to 103, and the router alone from 85 to 61 — it declines 74
# instead of 41, and the gated `buscar_en_curso` covers most of those. What it buys
# is the whole confident-wrong population: over the 44 off-topic customer messages in
# `queries.OFF_TOPIC` the tool named a lesson for 18 of them at FLOOR = 3.0 and
# for 3 at FLOOR = W_TERM — and all 3 of those are caught before ranking by
# `intent.py`, so the shipped number is 0.
#
# The relation is asserted in test_retrieval.py rather than left as a comment:
# W_PHRASE < FLOOR <= W_TERM. A future edit to any of the three weights that
# re-opens the coin-flip bucket goes red on that inequality, which a hand-picked
# 4.5 could not do.
FLOOR = W_TERM


def strip_accents(text: str) -> str:
    """Same normalisation Node does (NFD, drop the combining marks), so a query
    typed with accents and one typed without are the same query on both sides."""
    return "".join(c for c in unicodedata.normalize("NFD", text)
                   if not unicodedata.combining(c))


def stopwords(lang: Lang) -> frozenset[str]:
    return STOPWORDS_EN if lang == "en" else STOPWORDS_ES


def synonyms(lang: Lang) -> Mapping[str, tuple[str, ...]]:
    return SYNONYMS_EN if lang == "en" else SYNONYMS_ES


def stem(word: str) -> str:
    """A deliberately tiny stemmer: plural only.

    It is not trying to be a morphological analyser. It exists so `fotos`/`foto`,
    `puntajes`/`puntaje` and `weights`/`weight` are one key, and it is applied to
    BOTH sides of every comparison, so even where it is wrong it is wrong
    consistently and cannot invent a match that the other side does not share.

    It strips a trailing «s» and nothing else. An earlier version also stripped
    «es», which is the correct Spanish plural rule and a trap in English: it turned
    `writes` into `writ` while `write` stayed `write`, so the two stopped matching
    each other and «it writes one word at a time» routed to lesson 1 on the word
    `writes` instead of to lesson 6 on the word `word`. Being wrong CONSISTENTLY is
    the whole value of a stemmer this small; being wrong in one direction only
    breaks the invariant it exists for.
    """
    if len(word) >= 4 and word.endswith("s"):
        return word[:-1]
    return word


def words(text: str) -> tuple[str, ...]:
    """Every alphanumeric run in the text, lowercased and unaccented. No filtering
    yet: `ampliar_consulta` has to be able to report what it DROPPED, which means
    the drop has to happen after this and not inside it."""
    flat = strip_accents(str(text).lower())
    out: list[str] = []
    token: list[str] = []
    for ch in flat:
        if ch.isalnum():
            token.append(ch)
        elif token:
            out.append("".join(token))
            token = []
    if token:
        out.append("".join(token))
    return tuple(out)


@dataclass(frozen=True, slots=True)
class Prepared:
    """A query, taken apart. `dropped` travels so the trace can show it."""

    original: str
    kept: tuple[str, ...]          # the discriminating words, stemmed
    surface: tuple[str, ...]       # the same words as typed, for the report
    dropped: tuple[str, ...]       # stopwords and too-short words, as typed
    bridged: tuple[str, ...]       # glossary terms reached through a synonym


def prepare(query: str, lang: Lang = "es") -> Prepared:
    """Normalise, drop the stopwords, expand into the course's own vocabulary.

    The synonym pass runs over the SURFACE words rather than the stems, because the
    table is authored as whole words and a stem like `confi` would quietly widen
    `confiar` into `configurar`.
    """
    stops = stopwords(lang)
    syn = synonyms(lang)
    kept: list[str] = []
    surface: list[str] = []
    dropped: list[str] = []
    bridged: list[str] = []
    for w in words(query):
        if len(w) < MIN_WORD or w in stops:
            dropped.append(w)
            continue
        surface.append(w)
        kept.append(stem(w))
        for target in syn.get(w, ()):
            if target not in bridged:
                bridged.append(target)
    return Prepared(original=str(query), kept=tuple(kept), surface=tuple(surface),
                    dropped=tuple(dropped), bridged=tuple(bridged))


def _stems(text: str) -> frozenset[str]:
    """The CONTENT stems of a phrasing: stopwords of BOTH languages removed.

    Measured defect this fixes. Coverage is `shared / len(target)`, and the target
    used to include the question scaffolding, so «donde guarda lo que aprendio» — a
    phrasing of lesson 3, matched word for word by a query typed exactly that way —
    scored 2/4 coverage because `donde` and `que` were dropped from the QUERY (they
    are stopwords) and kept in the PHRASING. Half its coverage was spent on words
    the query side is not even allowed to contribute. The union of both stopword
    lists is used because a phrasing is matched against questions in either
    language: that is the same reason `terms()` is read for both.
    """
    stops = STOPWORDS_ES | STOPWORDS_EN
    return frozenset(stem(w) for w in words(text)
                     if len(w) >= MIN_WORD and w not in stops)


def _same(a: str, b: str) -> bool:
    """Two stems name the same thing.

    Equality, or a common prefix of six characters or more. The prefix rule is what
    connects `aprende` to `aprendizaje` and `entrenar` to `entrenamiento` without a
    per-word exception list. Six is the measured floor at which it stops being
    noise: at five, `contar` matches `contexto`.
    """
    if a == b:
        return True
    if len(a) < 6 or len(b) < 6:
        return False
    n = 0
    for x, y in zip(a, b, strict=False):
        if x != y:
            break
        n += 1
    return n >= 6


def _term_matched(term: str, present: Iterable[str]) -> bool:
    """A term counts only when EVERY word of it is present.

    Multi-word terms are why: `perilla creativa` must not fire on `perilla` alone,
    or lesson 9 would win every question about parameters. Requiring all the words
    is also what lets `perilla` (lesson 3) and `perilla creativa` (lesson 9)
    coexist in one map without one swallowing the other.
    """
    return bool(_term_stems(term, present))


def _term_stems(term: str, present: Iterable[str]) -> frozenset[str]:
    """WHICH query stems a term matched, empty when it did not match at all.

    Same rule as `_term_matched` — every word of the term has to be present — but it
    reports what was consumed, so `_score` can refuse to pay twice for one word of
    the question. Returning the set rather than a bool is the whole difference
    between «this term matched» and «this term matched something new».
    """
    have = tuple(present)
    parts = [stem(w) for w in words(term) if len(w) >= MIN_WORD]
    if not parts:
        return frozenset()
    used: set[str] = set()
    for p in parts:
        hit = [h for h in have if _same(p, h)]
        if not hit:
            return frozenset()
        used.update(hit)
    return frozenset(used)


# ---------------------------------------------------------------------------
# HOW DISCRIMINATING A WORD IS, measured over the MAP and not over the corpus
#
# The first version of this scorer gave every shared word the same value and
# routed 49% of the 138 measured queries correctly — WORSE than the substring
# counter it is compared against (51%, generated by scripts/emit-search-baseline.mjs
# rather than transcribed). The reason was visible the moment it was written down:
# `sabe` occurs in the phrasings of lessons 1, 3 and 11, `guarda` in lesson 3
# alone, and treating them alike lets the vaguest word in the sentence pick the
# lesson. That is the same defect as Node's stopword problem, one level up — a word
# that is everywhere deciding the answer.
#
# So a word is worth log((N + 1) / df) where df is how many CONCEPTS use it. A word
# unique to one concept is worth log(13) = 2.56 and clears the floor on its own; a
# word shared by six is worth 0.77 and cannot route anything by itself.
#
# The `+ 1` is not cosmetic smoothing. Without it a word present in EVERY concept is
# worth exactly log(1) = 0, and a map with one concept in it has every word at zero
# and cannot route at all. With it a universal word is worth log(13/12) = 0.08:
# still unable to route anything by itself, which is the property that was wanted,
# and no longer a special case.
#
# The result is then divided by log(N + 1), so a word unique to one concept is worth
# 1.0 whatever the size of the map. That matters because FLOOR is an absolute
# number: un-normalised, the same question scores differently against a map of 12
# concepts and a map of 3, and the floor would quietly mean something different for
# each — a scorer whose verdict depends on the size of its input rather than on the
# question. The division is by a constant, so every ratio inside one map is
# untouched: measured, the 138-question table scores identically before and after.
#
# WHY THIS IS NOT THE THING THIS MODULE REFUSES TO DO. The counts are taken over
# the authored phrasings and the public glossary terms in `concepts.py` — data this
# repository wrote. It is not a document frequency over `lessons.technical`, which
# would be a statistic derived from the paid corpus and would carry its vocabulary
# back in through the numbers. Nothing here has ever read a lesson.
@dataclass(frozen=True, slots=True)
class Weights:
    """How discriminating each word of a map is, plus the value for one it has not
    seen. `unknown` travels WITH the table instead of being recomputed from the
    shipped map, so ranking against an injected fixture stays self-consistent."""

    idf: Mapping[str, float]      # 0 < value <= 1, one unique word = 1.0
    unknown: float

    def of(self, word: str) -> float:
        """An unseen word is worth as much as a unique one, never more.

        A stem the map has never seen cannot be matched at all, so this is not the
        common path — but a query word that matched through the six-character prefix
        rule can be absent from the table while its partner is present, and
        defaulting it to 0.0 would silently discard the very matches that rule
        exists to find.
        """
        return self.idf.get(word, self.unknown)


@lru_cache(maxsize=8)
def _weights(concepts: tuple[Concept, ...]) -> Weights:
    df: dict[str, int] = {}
    for c in concepts:
        seen: set[str] = set()
        for text in (*phrasings(c), *terms(c)):
            seen |= _stems(text)
        for w in seen:
            df[w] = df.get(w, 0) + 1
    n = len(concepts) + 1
    ceiling = math.log(n)
    return Weights(idf={w: math.log(n / k) / ceiling for w, k in df.items()},
                   unknown=1.0)


@dataclass(frozen=True, slots=True)
class Reason:
    """WHY this concept scored. `kind` is one of `termino`, `sinonimo`, `frase`."""

    kind: str
    detail: str
    points: float


@dataclass(frozen=True, slots=True)
class Ranked:
    concept: Concept
    score: float
    reasons: tuple[Reason, ...]

    @property
    def confidence(self) -> float:
        """0..1, for the model to read. A ratio against a fixed ceiling rather than
        against the runner-up: a normalisation against the second place reports 1.0
        for a single weak hit, which is the most confident-sounding thing this can
        say about the least evidence it can have."""
        return round(min(self.score / 12.0, 1.0), 2)


def _score(prepared: Prepared, c: Concept,
           idf: Weights) -> tuple[float, tuple[Reason, ...]]:
    reasons: list[Reason] = []
    total = 0.0

    # Both languages' terms, always. `lessons` and `labs` have no `lang` column, so
    # an English session is already searching a mostly-Spanish corpus in Node;
    # refusing to match an English question against a Spanish term here would throw
    # away the only routing signal that language has.
    # ONE QUERY WORD PAYS ONCE. Measured defect: the glossary carries several
    # surface forms of the same idea (`aprendizaje` and `aprender`; `peso` and
    # `pesos`), and `aprendio` matched both, so a single word in the question was
    # worth 2x W_TERM = 10 points. «donde guarda lo que aprendio» — a phrasing of
    # lesson 3, typed word for word — routed to lesson 1 on that doubling alone.
    # Tracking which query stems a term consumed keeps the genuinely independent
    # case intact: «hay una perilla para la creatividad» still scores `perilla
    # creativa` AND `creatividad`, because those are two different words in the
    # question rather than one word counted twice.
    hit_terms: list[str] = []
    consumed: set[str] = set()
    for t in terms(c):
        if t in hit_terms:
            continue
        matched = _term_stems(t, prepared.kept)
        if matched and not matched <= consumed:
            hit_terms.append(t)
            consumed |= matched
            total += W_TERM
            reasons.append(Reason("termino", t, W_TERM))

    for t in terms(c):
        if t in hit_terms:
            continue                      # already counted, and at the higher weight
        if any(_same(stem(b), stem(t)) or b == t for b in prepared.bridged):
            total += W_SYNONYM
            reasons.append(Reason("sinonimo", t, W_SYNONYM))
            hit_terms.append(t)

    # The best single phrasing, not the sum: a concept with twenty phrasings must
    # not out-score one with six by volume. What is summed inside one phrasing is
    # the DISCRIMINATING WEIGHT of the words shared with the query, so overlapping
    # on `guarda` (lesson 3 only) is worth three times overlapping on `sabe`
    # (lessons 1, 3 and 11).
    best = 0.0
    best_detail = ""
    for p in phrasings(c):
        target = _stems(p)
        if not target:
            continue
        # ONE QUERY WORD PAYS ONCE — ACROSS SIGNALS, not only inside the terms
        # loop above. `consumed` holds the query stems a term already paid for, and
        # a phrasing overlapping on the SAME query word is not new evidence: it is
        # one word of the question billed twice.
        #
        # Measured defect. «donde guarda lo que aprendio» is a phrasing of lesson 3
        # typed word for word, and it routed to lesson 1: there the single word
        # `aprendio` paid once as the term `aprendizaje` (5.0) and again as an
        # overlap on the phrasing «que es el aprendizaje automatico» (4.1) — 9.10
        # from ONE word, out-scoring lesson 3's 8.21 built from TWO, one of them
        # `guarda`, which no other concept in the map uses. Excluding the consumed
        # stems leaves lesson 1 at 5.0 and the verbatim phrasing wins.
        shared = [w for w in target
                  if any(_same(w, k) for k in prepared.kept if k not in consumed)]
        if not shared:
            continue
        value = W_PHRASE * sum(idf.of(w) for w in shared)
        if value > best:
            best = value
            best_detail = p
    if best > 0:
        total += best
        reasons.append(Reason("frase", best_detail, round(best, 2)))

    return total, tuple(reasons)


def rank(query: str, lang: Lang = "es", *,
         concepts: Sequence[Concept] = CONCEPTS,
         limit: int = 3) -> tuple[Ranked, ...]:
    """The concepts this question is about, best first, above the floor only.

    An empty result is a real answer and the important one: it means «say you do not
    know», not «pick the least bad lesson». `concepts` is injectable so a test can
    rank against a fixture map instead of the shipped one.
    """
    prepared = prepare(query, lang)
    idf = _weights(tuple(concepts))
    scored: list[Ranked] = []
    for c in concepts:
        total, reasons = _score(prepared, c, idf)
        if total >= FLOOR:
            scored.append(Ranked(c, round(total, 2), reasons))
    # The tie-break is the lesson number, so the same question always produces the
    # same answer. A tie broken by dict order changes with an edit somewhere else.
    scored.sort(key=lambda r: (-r.score, r.concept.leccion))
    return tuple(scored[:limit])


def rewrite(query: str, lang: Lang = "es", *, limit: int = 3) -> tuple[str, ...]:
    """The query strings to hand to the bridged `buscar_en_curso`, best first.

    The first is the discriminating words alone — which is already an improvement,
    because it is the original with the words that match everything taken out. The
    rest put the course's OWN vocabulary in front, since that is what the corpus
    actually contains: the beginner's `aleatorio` is not in twelve lessons and
    `temperatura` is in one.
    """
    prepared = prepare(query, lang)
    out: list[str] = []
    if prepared.surface:
        out.append(" ".join(prepared.surface))
    for r in rank(query, lang, limit=limit):
        for t in r.concept.terms_es[:1] + r.concept.terms_en[:1]:
            candidate = f"{t} {' '.join(prepared.surface[:3])}".strip()
            if candidate not in out:
                out.append(candidate)
    return tuple(out[:limit])
