// Command trinity is line 2: the walls.
//
// sshd, the listening sockets, and the firewall ruleset. Trinity reports; it
// does not apply. Applying a firewall from an agent is how a box locks its owner
// out, and on a Pi behind CGNAT at somebody's house, locking the owner out means
// a physical trip with a keyboard.
//
// `trinity nft` prints the ruleset to apply BY HAND, or from a deploy step that a
// human triggered. It is on stdout so it can be reviewed, diffed and version
// controlled before it ever touches the kernel.
package main

import (
	"context"
	"fmt"
	"os"
	"strings"

	"course/defense/internal/agent"
	"course/defense/internal/finding"
	"course/defense/internal/probe"
)

func main() {
	if len(os.Args) > 1 && os.Args[1] == "nft" {
		fmt.Print(Ruleset())
		return
	}
	os.Exit(agent.Run("trinity", scan))
}

func scan(_ context.Context) []finding.Finding {
	var out []finding.Finding

	sshd, miss := agent.ReadOrReport("/etc/ssh/sshd_config", "host.ssh", finding.Host, "trinity")
	if miss != nil {
		out = append(out, *miss)
	} else {
		out = append(out, probe.SSHConfig(sshd)...)
	}

	tcp, miss := agent.ReadOrReport("/proc/net/tcp", "host.listeners", finding.Host, "trinity")
	if miss != nil {
		out = append(out, *miss)
	} else if ls, err := probe.ParseProcNetTCP(tcp, false); err != nil {
		out = append(out, finding.Finding{
			Rule: "host.listeners.unparsed", Line: finding.Host, Source: "trinity",
			Severity: finding.Low, Target: "/proc/net/tcp",
			Summary: "could not parse /proc/net/tcp",
			Remedy: "this is a bug in probe.ParseProcNetTCP, not a configuration problem. Until it " +
				"is fixed the listening-socket check reports nothing",
			Evidence: map[string]string{"error": err.Error()},
		})
	} else {
		out = append(out, probe.WildcardListeners(ls)...)
	}

	// Unattended upgrades. An unpatched Pi is the most likely way this box is
	// lost, and it is the cheapest thing on this list to fix.
	if _, err := os.Stat("/etc/apt/apt.conf.d/20auto-upgrades"); os.IsNotExist(err) {
		out = append(out, finding.Finding{
			Rule: "host.updates.unattended_missing", Line: finding.Host, Source: "trinity",
			Severity: finding.Medium, Target: "apt",
			Summary: "unattended-upgrades is not configured",
			Remedy: "apt install unattended-upgrades && dpkg-reconfigure -plow unattended-upgrades. " +
				"An unpatched box is the most likely way this Pi is lost, and this is the cheapest " +
				"item on the whole list",
			Evidence: map[string]string{"looked_for": "/etc/apt/apt.conf.d/20auto-upgrades"},
		})
	}
	return out
}

// Ruleset is the nftables policy, as text, from a pure function so it can be
// asserted in a test rather than reviewed by eye.
//
// THE TWO THINGS THIS MUST NOT BREAK, both of them learned the hard way:
//
//   - MOSQUITTO on 1883. It is not part of this project; it serves the ESP32s on
//     the LAN and the standing instruction is to leave it running. A default-drop
//     ruleset that forgets it silently kills every sensor in the house.
//   - SSH from the LAN. This box is behind CGNAT in a home, so a lockout is a
//     physical trip with a monitor and a keyboard.
func Ruleset() string {
	var b strings.Builder
	b.WriteString(`#!/usr/sbin/nft -f
# Generated by `)
	b.WriteString("`trinity nft`")
	b.WriteString(`. Review it, commit it, then apply it deliberately:
#
#     trinity nft > /etc/nftables.conf && nft -f /etc/nftables.conf
#
# It is NOT applied by any agent. A firewall applied automatically on a box
# behind CGNAT in somebody's house is one false positive away from a trip with a
# keyboard.

flush ruleset

table inet defense {
  # The 'banned' set is what policy.BanHostIP adds to, and every element carries a
  # KERNEL-SIDE timeout. That is deliberate: a timer inside an agent dies with
  # the agent, and the ban it was going to remove becomes permanent.
  set banned {
    type ipv4_addr
    flags timeout
    timeout 1h
  }

  chain input {
    type filter hook input priority filter; policy drop;

    # Established traffic first: without this rule every reply to a connection
    # this box opened is dropped, which looks like the network is broken rather
    # than like a firewall.
    ct state established,related accept
    iif lo accept
    ct state invalid drop

    ip saddr @banned drop

    # ICMP echo stays. Dropping ping on a home LAN buys nothing and removes the
    # first diagnostic anybody reaches for.
    ip protocol icmp icmp type { echo-request, echo-reply, destination-unreachable, time-exceeded } accept
    ip6 nexthdr icmpv6 accept

    # SSH from the LAN only. There is no inbound path from the internet on a
    # CGNAT connection, so this is not an internet-facing rule -- it is what
    # keeps a compromised device on the home network from reaching sshd.
    ip saddr { 192.168.0.0/16, 10.0.0.0/8 } tcp dport 22 accept

    # MOSQUITTO. NOT part of this project. The ESP32s speak to it over the LAN
    # and it must keep working; removing this line takes every sensor offline.
    ip saddr { 192.168.0.0/16, 10.0.0.0/8 } tcp dport 1883 accept

    # NOTHING for the application. Every request arrives through cloudflared,
    # which makes an OUTBOUND connection to Cloudflare and needs no inbound
    # port at all. If you find yourself adding a dport here for the api or the
    # web, the tunnel is misconfigured and opening a hole is not the fix.

    log prefix "defense-drop " flags all limit rate 5/minute
  }

  chain forward {
    # Docker manages its own forwarding rules in the ip filter table; this
    # chain deliberately does not fight it. Setting policy drop here breaks
    # container networking in a way that takes an hour to diagnose.
    type filter hook forward priority filter; policy accept;
  }

  chain output {
    type filter hook output priority filter; policy accept;
  }
}
`)
	return b.String()
}
